repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: end-of-file-fixer
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.4.0
    hooks:
    -   id: reorder-python-imports
        types: [python]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-yaml
        exclude: meta.yaml
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.9.2
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black]
        types: [rst]
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        types: [python]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        types: [python]
        exclude: estimagic/optimization/kernel_transformations.py
        additional_dependencies: [
            flake8-alfred, flake8-bugbear, flake8-builtins, flake8-comprehensions,
            flake8-docstrings, flake8-eradicate, flake8-print, flake8-rst-docstrings,
            flake8-todo, pep8-naming, pydocstyle,
        ]
-   repo: https://github.com/PyCQA/doc8
    rev: 0.9.0a1
    hooks:
        -   id: doc8
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
    # -   id: identity  # Prints all files passed to pre-commits. Debugging.
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 0.5.9
    hooks:
    -   id: nbqa-black
        additional_dependencies: [black==20.8b1]
    -   id: nbqa-pyupgrade
        additional_dependencies: [pyupgrade==2.7.3]
        exclude: 'inference|differentiation|miscellaneous'
    -   id: nbqa-isort
        additional_dependencies: [isort==5.6.4]
-   repo: https://github.com/PyCQA/doc8
    rev: 0.9.0a1
    hooks:
    -   id: doc8
